"""empty message

Revision ID: 13cdb3f2d173
Revises: 78545d7b79be
Create Date: 2024-09-26 21:23:51.731536

"""
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = '13cdb3f2d173'
down_revision: str | None = '78545d7b79be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
